### PR TITLE
Fixed a few more waitKey commands

### PR DESCRIPTION
**Pull request by terfendail**
I've updated a few more waitKey calls. I think it make sense to add the update to already existing PR.

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Thank you!

**Comment by StevenPuttemans** [comment]
Ah damn, @terfendail , I accidently forced updated my local branch at work again, removing your addons from the PR. Do you still got em locally? If not I will add them myself! Sorry for the hassle!

**Comment by terfendail** [comment]
I've restored the branch. I could recreate PR if it is necessary.

**Comment by StevenPuttemans** [comment]
That did not do the trick, but just copy pasted your edits. should be okay now :+1:

**Pull request merged**
